[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log

[program:xvfb]
command=/usr/bin/Xvfb %(ENV_DISPLAY)s -screen 0 %(ENV_DISPLAY_RESOLUTION)s -nolisten tcp
priority=10
autorestart=true
stdout_logfile=/tmp/xvfb.log
stderr_logfile=/tmp/xvfb.err.log

[program:openbox]
command=/usr/bin/openbox
environment=DISPLAY="%(ENV_DISPLAY)s"
priority=20
autorestart=true
startretries=100
stdout_logfile=/tmp/openbox.log
stderr_logfile=/tmp/openbox.err.log

[program:x11vnc]
command=/usr/bin/x11vnc -display %(ENV_DISPLAY)s -forever -shared -nopw -rfbport %(ENV_VNC_PORT)s -xkb -noxrecord -noxfixes -noxdamage
environment=DISPLAY="%(ENV_DISPLAY)s"
priority=20
autorestart=true
startretries=100
stdout_logfile=/tmp/x11vnc.log
stderr_logfile=/tmp/x11vnc.err.log

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ %(ENV_NOVNC_PORT)s localhost:%(ENV_VNC_PORT)s
priority=30
autorestart=true
startretries=100
stdout_logfile=/tmp/novnc.log
stderr_logfile=/tmp/novnc.err.log

[program:mower_simulation]
command=/bin/bash -lc 'source /opt/ros/%(ENV_ROS_DISTRO)s/setup.bash && source /opt/open_mower_ros/devel/setup.bash && exec roslaunch /opt/mower_simulation_gui.launch --screen'
environment=DISPLAY="%(ENV_DISPLAY)s",LIBGL_ALWAYS_SOFTWARE="%(ENV_LIBGL_ALWAYS_SOFTWARE)s"
priority=40
autorestart=true
startretries=100
startsecs=5
stdout_logfile=/tmp/mower_simulation.log
stderr_logfile=/tmp/mower_simulation.err.log
